### ISSUE TITLE
How to get defaults from schema instead of from v-model on mount

### ISSUE THREAD

**Issue by Rednas83** [formkit/formkit#1425]
### Reproduction

https://formkit.link/29132d186d3cd07dbfa5c2daa6d44a10

### Describe the bug

I would like to ignore the `v-model values` on mount and use the `schema values` instead.
`<FormKit type="group" v-model="data" @input="$emit('input', $event)"> <FormKitSchema v-if="schema" :schema="schema" /> </FormKit>`

The reason is that I am populating the `schema` based on the `v-model `with a scheme function and I would prefer to only use 1 model for it for simplicity.

For example I am pushing a number and options like this
**v-model**
```
{
age: 41,
error-behaviour: 'blur || submit || live' // SELECT
parameters: HSP=60Hz OFFD=50mm // LIST
i_Command: 0=Auto 1=CW 2=CCW 3=Pauze 4=Resume 5=Reset // TOGGLEBUTTONS
options: 'abc=>a;b;c || de=>d;e || f' // TREE
options: 'First || Second t-taglist' // TAGLIST
iObject: {world: 'Sander t-keys'} // KEYS
validation: 'javascript || typescript t-autocomplete' // AUTOCOMPLETE
state: 'design || review || produce || test t-stepper' // STEPPER
command: StartStop // TOGGLEBUTTONS
}
```
**schema**
```
// age: 41
case "number":
  var min=iSettings[item]?.min || unit.min || 100
  var max=iSettings[item]?.max || unit.max || 0
  var middle=(max-min)/2
  result.push({
    $formkit: "slider",
    name: item,
    label: unit.unit ? `${iLabel} (${unit.unit})` : iLabel,
    min: iSettings[item]?.min || unit.min,
    max: iSettings[item]?.max || unit.max,
    value: iTable[item],
    tooltip: true,
    marks:[
      { at: min, label: `${min}${unit.unit}` },              
      { at: middle, label: `${middle}${unit.unit}` },
      { at: max, label: `${max}${unit.unit}` },
    ],
    help: "-", // WORKAROUND: Otherwise the label is not fully shown
  })
  // error-behaviour: 'blur || submit || live' => SELECT
  // parameters: HSP=60Hz OFFD=50mm => LIST
  // i_Command: 0=Auto 1=CW 2=CCW 3=Pauze 4=Resume 5=Reset => TOGGLEBUTTONS
  // options: 'abc=>a;b;c || de=>d;e || f' => TREE
  // options: 'First || Second t-taglist' => TAGLIST
  // iObject: {world: 'Sander t-keys'} => KEYS
  // validation: 'javascript || typescript t-autocomplete' => AUTOCOMPLETE
  // state: 'design || review || produce || test t-stepper' => STEPPER
  // command: StartStop => TOGGLEBUTTONS
  else {
    const props = {
      $formkit: options.type,
      name: item,
      label: item == "state" || options.type == "prompt" ? undefined : iLabel,
      value: options.default || options.value,
      options: options.default ? options.value : undefined,
      multiple: isMultiple || isBoolean ? true : false,
      // TODO https://github.com/formkit/formkit/issues/1395
    }              

    if (options.type == "keys" || options.type == "stepper") {
      result.push({
        $cmp: options.type,
        props: props.deletex("$formkit"),
      })
    } else {
      result.push(props)
    }
  }
```

It's still a work in progress but I can of course share when it's ready. The idea is to translate actual data into a form directly.

Something like
```
---
ID: 1
I_Enable: auto-default || cw-default || ccw || pauze || resume || slow || fast is-boolean
I_Command: 0=Auto 1=CW 2=CCW 3=Pauze 4=Resume 5=Reset
IBS: {
    DIGITAL: AO || SWS || CFOE || SOP, # Digital inputs
    SI: 1000hours, # Service interval
    FDBD: 0s, # Feedback delay
    STAD: 0s, # Start delay
    STOD: 0s, # Stop delay
    OFFD: 0s, # Off delay
    SPD0: 50rpm, # Acive speed
    SPD1: 500rpm △0.5s, # Slowdown/Normal speed
    SPD2: 1500rpm △1s, # Normal speed
    SPD3: 1800rpm △1s, # High speed
  }
MotorData: {
    ETA: 25, # Status
    LCR: 25.0, # Motor current
    OTR: 25.0, # Motor torque
    OPR: 25.0, # Motor power
    LFT: 25, # Last fault
    RFRD: 25, # Output velocity
  }
ChainIn:
  { Command: 0=Off 1=Start 2=Stop 3=Pauze 4=Resume 5=Reset, State: 0=Idle-default 1=Running 10=Holding 11=Held 12=Restarting 20=Pausing 21=Paused }
---
```

### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      telemetry, modules, experimental, icon, build, routeRules, components, content, formkit, imports, css, devtools
- Runtime Modules:  @vueuse/nuxt@10.11.0, normalizedModule(), @nuxt/content@2.13.0, @nuxtjs/tailwindcss@6.12.0, @nuxt/icon@1.0.0, @formkit/nuxt@1.6.5, @nuxt/icon@1.0.0
- Build Modules:    -
------------------------------

```
