### ISSUE TITLE
Only thing holding me back from using Formkit is lack of a Bootstrap integration guide

### ISSUE THREAD

**Issue by dosstx** [formkit/formkit#500]
### Describe the feature

Is there any chance someone can write a guide on how to integrate with Bootstrap 5 styles? I admit the only thing holding me back from using Formkit is the lack of Bootstrap integration support (I see there is a Tailwind guide). I know of others that are in the same boat and think this feature will be useful to other developers.

**Comment by devoidofgenius** [comment]
We appreciate you raising this issue. While it's not on our current roadmap we will consider adding more styling guides in the future. If you're not a member in our [Discord community](https://discord.gg/Vhu97pAC76) already, I encourage you to join. I'm positive plenty of good folks over there would be willing to help you out with the issues you face using Bootstrap with FormKit.

**Comment by Stiropor** [comment]
@dosstx I just stubled upon this and thought I'd share my findings. This is how I'm using FormKit with Bootstrap 5.3 and so far it works great. You do need to make sure you set the scss variables for Bootstrap also, might also work without it. The config also includes a plugin (found on Discord by some user) that allows you to use floating labels if uncommented. So....

Using: `formkit.config.js`
```javascript
import { generateClasses } from '@formkit/themes'
import { en } from '@formkit/i18n'
import { clone } from '@formkit/utils'

/**
 * Plugin for floating labels where the label is placed after the input. To use add .form-floating inner class to text, email, textarea and select elements.
 * Source: https://github.com/formkit/formkit/issues/174
 *
 * @param node
 */
const useFloatingLabels = function (node) {
	node.on('created', () => {
		const inputDefinition = clone(node.props.definition)
		if (['radio', 'checkbox', 'button', 'submit'].includes(node.props.type)) { return }
		const originalSchema = inputDefinition.schema
		const higherOrderSchema = (extensions) => {
			// This kills the original label
			extensions.label = { $el: null, children: null }
			extensions.suffix = {
				$el: 'label',
				children: '$label',
				attrs: {
					'data-has-value': '$_value !== "" && $_value !== undefined',
					class: '$classes.floating',
					for: '$id'
				}
			}
			return originalSchema(extensions)
		}
		// Set placeholder as Bootstrap requires it
		node.props.attrs.placeholder = node.props.attrs.placeholder || node.props.label
		node.props.innerClass = [node.props.innerClass, 'form-floating'].join(' ')
		inputDefinition.schema = higherOrderSchema
		node.props.definition = inputDefinition
	})
}

const config = {
	locales: { en },
	locale: 'en',
	plugins: [
		// useFloatingLabels  // Uncomment for floating labels
	],
	config: {
		classes: generateClasses({
			global: { // applies to all input types
				outer: '$reset form-group',
				input: 'form-control',
				label: 'form-label',
				messages: 'list-unstyled small mb-0',
				message: 'is-invalid',
				help: 'form-text'
			},
			checkbox: {
				label: 'form-check-label',
				wrapper: 'checkbox-wrapper',
				inner: 'form-check',
				input: '$reset form-check-input',
				legend: '$reset form-check-label'
			},
			select: {
				input: '$reset form-select'
			},
			radio: {
				label: 'form-check-label',
				wrapper: 'radio-wrapper',
				inner: 'form-check',
				input: '$reset form-check-input',
				legend: '$reset form-check-label'
			},
			submit: {
				outer: '$reset mt-3',
				input: '$reset btn btn-primary'
			}
		})
	}
}

export default config
```

Note:  Bootstrap 5 isn't using `.form-group` anymore but I've added it to my scss because I find it dumb to use `.mb-*` or something, it's easier to style or change then :)

And this is my `_formkit-overrides.scss`:

```scss
.form-wrapper {
	@extend .row; // This is so you can use like outerClass: 'col-md-6' on a field and it shows on 50%
}

.radio-wrapper,
.checkbox-wrapper, {
	display: flex;

	.checkbox-label,
	.radio-label {
		margin-left: 0.5rem;
	}
}

.formkit-message {
	&.is-invalid {
		color: $danger;
	}
}

.formkit-input {
	[data-invalid="true"] & {
		border-color: $danger;
	}
}

.formkit-options {
	list-style: none;
	margin: 0;
	padding: 0;

	.form-check-inline & {
		display: flex;
		gap: 1rem;
	}
}
```

Hope it helps anyone 😃
