### ISSUE TITLE
Floating label plugin should hide placeholder

### ISSUE THREAD

**Issue by Tragio** [formkit/formkit#574]
### Reproduction

https://formkit.link/4018da7bad6990d43c4237fbe28f75bf

### Describe the bug

The floating label plugin should hide the placeholder automatically to avoid a collision. 😄 

Solutions given:
```css
[data-floating-label="true"]  .formkit-input:not(:focus)::placeholder { color: transparent; }
```

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]
