### ISSUE TITLE
Using a placeholder in a select applies the placeholder color to the options

### ISSUE THREAD

**Issue by arjendejong12** [formkit/formkit#59]
**Describe the bug**
When using a placeholder in a select, all options are gray but change to black when you pick an option. This is because of the following css rule:
```css
select.formkit-input[data-placeholder]:not([multiple]) {
    color: var(--fk-color-placeholder);
}
```
If you haven't picked an option yet, you can't make the distinction between selectable and disabled options, because both are gray.

**Reproduction**
https://formkit.link/3b592b04ed973531dd508820ba7d68dd

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 97
