### ISSUE TITLE
Mask and DatePicker issue with Floating Label Plugin

### ISSUE THREAD

**Issue by shoaibsharif** [formkit/formkit#777]
### Reproduction

https://formkit.link/8e1dd443d03b687d09f9b62642318d2d

### Describe the bug

When I pre-filled value via ref on Mask or DatePicker Input, it's not showing the value. But when I focus on the inputs it shows the value.

![CleanShot 2023-06-19 at 12 15 30](https://github.com/formkit/formkit/assets/29075110/ebffa106-889e-4bfe-83cf-2f7460f56777)
![CleanShot 2023-06-19 at 12 13 39](https://github.com/formkit/formkit/assets/29075110/29067db9-89bf-4124-bbb8-1aaf933eae3b)

### Environment

• OS: [MacOS]
• Browser [Arc, Chrome]
• Version [0.17.x]

**Comment by glennlaysonjr** [comment]
This is a issue with the CSS and not having target to look at on the input if there is a value in FormKit input. Right now the color is being controlled by:

```css
[data-floating-label="true"][data-type="mask"]:not(:focus-within) input,
[data-floating-label="true"][data-type="datepicker"] input {
  transition-duration: 0.2s;
  transition-delay: 0.1s;
  color: transparent; /* causing issue above */
}
```

Possible simple addition to formkit to fix above issue:

if used the same `data-has-value="true"` found on the floating label element and adding it to the sibling input (with same functionally as the label) you could then target the input to set the color in CSS to `color: inherit;`
