### ISSUE TITLE
Missed semicolon in `multistep.css`

### ISSUE THREAD

**Issue by toddeTV** [formkit/formkit#783]
### Reproduction

https://github.com/formkit/formkit/blob/2e81d151a69eb3a846abad5d64787ac10e8ea46d/packages/addons/src/css/multistep.css#LL7C7-L7C45

### Describe the bug

The `multistep.css` is missing a semicolon and cannot be build as import in pure CSS this way:

https://github.com/formkit/formkit/blob/2e81d151a69eb3a846abad5d64787ac10e8ea46d/packages/addons/src/css/multistep.css#LL7C7-L7C45

```css
:root {
  --multistep-color-border: #ccccd7;
  --multistep-color-tab: #eeeef4;
  --multistep-color-tab-active: #ffffff;
  --multistep-color-success: #54A085;
  --multistep-color-danger: #ea0000;
  --multistep-color-tab-active-text: #000000
  --multistep-color-tab-text: #767676;
  --multistep-radius: 0.4em;
  --multistep-shadow: 0.25em 0.25em 1em 0 rgb(0 0 0 / 10%);
}
```

Throwing:

```
ERROR  Internal server error: [...]:[...]:[...]: Missed semicolon
```

### Environment

```json
{
  "devDependencies": {
    "@formkit/addons": "^0.17.3",
    "@formkit/nuxt": "^0.17.3",
    "@formkit/pro": "^0.112.6",
    "@formkit/themes": "^0.17.3",
  }
}
```
