### ISSUE TITLE
Automatically detect background color for floating labels

### ISSUE THREAD

**Issue by AnthonyRuelle** [formkit/formkit#875]
### Reproduction

https://formkit.link/192616ac5683358c074991bb2ac676d1

### Describe the bug

When the form's background color is not white, we see that a white background color is added to the floating label.
It should be easy to change this background color or it should be done automatically.

<img width="385" alt="image" src="https://github.com/formkit/formkit/assets/93582464/f7eb8dbc-6f8e-4de4-8327-9de7e2366b02">

### Environment

• OS: All
• Browser Chrome
• Version Beta 17

**Comment by GustavoFenilli** [comment]
You can change that using CSS as you're using genesis
```css
[data-floating-label=true] input:focus~.formkit-label {
  background-color: lightgrey;
}
```
